name: causalrlbreaker

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - git
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - pip:
      - -r requirements.txt
